function app() {
    return {
        scrolled: false,
        modal: false,
        sel: null,
        showTop: false,
        presidents: [
            {id:1,init:'SN',name:'Ir. Soekarno',title:'Presiden ke-1 RI',years:'1945 — 1967',term:'22 tahun',born:'6 Juni 1901, Surabaya',died:'21 Juni 1970, Jakarta',party:'PNI / Non-Partai',vp:'Mohammad Hatta',short:'Proklamator kemerdekaan dan Presiden pertama Indonesia. Bapak Bangsa.',bio:'Ir. Soekarno adalah Presiden pertama Republik Indonesia yang menjabat dari tahun 1945 hingga 1967. Beliau adalah proklamator kemerdekaan Indonesia bersama Mohammad Hatta.',achieve:['Memproklamasikan kemerdekaan Indonesia pada 17 Agustus 1945','Menyusun Pancasila sebagai dasar negara','Memimpin Konferensi Asia-Afrika di Bandung tahun 1955','Membangun Monumen Nasional (Monas)','Pendiri Gerakan Non-Blok'],tags:['Proklamator','Bapak Bangsa','Pancasila']},
            {id:2,init:'SH',name:'Jenderal Besar TNI Soeharto',title:'Presiden ke-2 RI',years:'1967 — 1998',term:'32 tahun',born:'8 Juni 1921, Kemusuk',died:'27 Januari 2008, Jakarta',party:'Golkar',vp:'Sri Sultan HB IX, Adam Malik, dll',short:'Presiden terlama Indonesia. Era Orde Baru dengan pembangunan ekonomi masif.',bio:'Jenderal Besar TNI (Purn.) Soeharto adalah Presiden kedua Indonesia yang menjabat selama 32 tahun. Di bawah kepemimpinannya, Indonesia mengalami pertumbuhan ekonomi yang signifikan.',achieve:['Mencapai swasembada pangan pada tahun 1984','Membangun infrastruktur jalan tol dan bendungan','Menurunkan angka kemiskinan dari 60% menjadi 11%','Mengembangkan program Keluarga Berencana (KB)','Membangun industri strategis nasional'],tags:['Orde Baru','Pembangunan','Swasembada']},
            {id:3,init:'BJH',name:'Prof. Dr. Ing. B.J. Habibie',title:'Presiden ke-3 RI',years:'1998 — 1999',term:'1 tahun 5 bulan',born:'25 Juni 1936, Parepare',died:'11 September 2019, Jakarta',party:'Golkar',vp:'—',short:'Presiden transisi reformasi. Bapak Teknologi Indonesia.',bio:'Prof. Dr. Ing. H. B.J. Habibie adalah Presiden ketiga Indonesia yang dikenal sebagai Bapak Teknologi Indonesia.',achieve:['Mengembangkan pesawat N-250 Gatotkaca','Membuka era kebebasan pers dan demokratisasi','Membebaskan tahanan politik','Mengembangkan industri strategis IPTN','Mengadakan pemilu demokratis pertama (1999)'],tags:['Reformasi','Teknologi','Demokratisasi']},
            {id:4,init:'AW',name:'KH. Abdurrahman Wahid (Gus Dur)',title:'Presiden ke-4 RI',years:'1999 — 2001',term:'2 tahun',born:'7 Agustus 1940, Jombang',died:'30 Desember 2009, Jakarta',party:'PKB',vp:'Megawati Soekarnoputri',short:'Presiden pertama dari kalangan ulama. Tokoh pluralisme.',bio:'KH. Abdurrahman Wahid atau Gus Dur adalah Presiden keempat Indonesia dan presiden pertama dari kalangan ulama.',achieve:['Membubarkan Departemen Sosial yang korup','Mengakui Konghucu sebagai agama resmi','Memperkuat otonomi daerah','Mendorong dialog antar agama','Mencabut larangan ekspresi budaya Tionghoa'],tags:['Pluralisme','Toleransi','Ulama']},
            {id:5,init:'MS',name:'Megawati Soekarnoputri',title:'Presiden ke-5 RI',years:'2001 — 2004',term:'3 tahun',born:'23 Januari 1947, Yogyakarta',died:'— (Masih hidup)',party:'PDI-P',vp:'Hamzah Haz',short:'Presiden perempuan pertama Indonesia. Putri Soekarno.',bio:'Hj. Megawati Soekarnoputri adalah Presiden kelima Indonesia dan presiden perempuan pertama.',achieve:['Presiden perempuan pertama Indonesia','Menstabilkan perekonomian pasca krisis 1998','Mengembangkan industri kreatif','Memperkuat pertahanan dan keamanan','Melahirkan UU Sistem Pendidikan Nasional'],tags:['Perempuan Pertama','Stabilitas','PDI-P']},
            {id:6,init:'SBY',name:'Jenderal TNI (Purn.) Susilo Bambang Yudhoyono',title:'Presiden ke-6 RI',years:'2004 — 2014',term:'10 tahun',born:'9 September 1949, Pacitan',died:'— (Masih hidup)',party:'Demokrat',vp:'Jusuf Kalla (2004-2009), Boediono (2009-2014)',short:'Presiden pertama terpilih langsung oleh rakyat.',bio:'Jenderal TNI (Purn.) Susilo Bambang Yudhoyono adalah presiden pertama yang terpilih langsung oleh rakyat.',achieve:['Presiden pertama terpilih langsung oleh rakyat','Mencapai pertumbuhan ekonomi 6% per tahun','Mengembangkan program bantuan sosial (BLT, PKH)','Memperkuat hubungan internasional','Mendorong pembangunan pedesaan'],tags:['Demokrasi','Pertumbuhan','Reformasi']},
            {id:7,init:'JW',name:'Ir. H. Joko Widodo (Jokowi)',title:'Presiden ke-7 RI',years:'2014 — 2024',term:'10 tahun',born:'21 Juni 1961, Surakarta',died:'— (Masih hidup)',party:'PDI-P',vp:'Jusuf Kalla (2014-2019), KH. Ma\'ruf Amin (2019-2024)',short:'Presiden dari rakyat biasa. Fokus infrastruktur dan SDM.',bio:'Ir. H. Joko Widodo atau Jokowi adalah presiden pertama yang bukan dari kalangan elite militer atau politisi karir.',achieve:['Membangun jalan tol Trans-Jawa dan Trans-Sumatera','Mengembangkan program KIP dan KIS','Membangun MRT Jakarta dan LRT Jabodebek','Mendorong hilirisasi industri tambang','Membangun ibu kota baru Nusantara'],tags:['Infrastruktur','SDM','Hilirisasi']},
            {id:8,init:'PS',name:'Jenderal TNI (Purn.) H. Prabowo Subianto',title:'Presiden ke-8 RI',years:'2024 — sekarang',term:'Saat ini',born:'17 Oktober 1951, Jakarta',died:'— (Masih hidup)',party:'Gerindra',vp:'Gibran Rakabuming Raka',short:'Presiden petahana. Fokus pertahanan dan ketahanan pangan.',bio:'Jenderal TNI (Purn.) H. Prabowo Subianto adalah Presiden kedelapan Indonesia yang dilantik pada Oktober 2024.',achieve:['Presiden terpilih 2024','Mantan Menteri Pertahanan','Fokus pada ketahanan pangan','Mendorong kedaulatan energi','Melanjutkan pembangunan ibu kota Nusantara'],tags:['Pertahanan','Pangan','Keberlanjutan']}
        ],
        init() {
            window.addEventListener('scroll', () => { this.scrolled = window.scrollY > 50; this.showTop = window.scrollY > 400; });
        },
        open(p) { this.sel = p; this.modal = true; document.body.style.overflow = 'hidden'; },
        close() { this.modal = false; this.sel = null; document.body.style.overflow = ''; }
    };
}

function closeMenu() {
    document.querySelector('.hamburger')?.classList.remove('active');
    document.querySelector('.nav-menu')?.classList.remove('show');
}
